# -*- coding: utf-8 -*-
"""Builds Output/EnigmaCube-Setup-<version>.exe (run on Windows).

Steps:
  1. the app    -> dist/EnigmaCube/  (one folder; it also uninstalls itself:
                   EnigmaCube.exe --uninstall)
  2. payload    -> build/payload.zip (the app folder + payload.json)
  3. the setup  -> Output/EnigmaCube-Setup-<version>.exe (one file)

Parts of Qt that a widgets app never uses (software OpenGL, ANGLE, Qt
translations, extra plugins) are left out to keep the download small.
"""

import json
import os
import re
import subprocess
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INST = os.path.join(ROOT, "installer")
BUILD = os.path.join(ROOT, "build")

DROP = [
    "opengl32sw.dll", "d3dcompiler_47.dll", "libegl.dll", "libglesv2.dll",
    "qt5/translations/", "qt5/plugins/iconengines/", "qt5svg.dll",
    "qt5/plugins/imageformats/qgif", "qt5/plugins/imageformats/qicns",
    "qt5/plugins/imageformats/qsvg", "qt5/plugins/imageformats/qtga",
    "qt5/plugins/imageformats/qtiff", "qt5/plugins/imageformats/qwbmp",
    "qt5/plugins/imageformats/qwebp", "qt5/plugins/platforms/qminimal",
    "qt5/plugins/platforms/qwebgl",
    "qt5qml", "qt5quick", "qt5network", "qt5websockets", "qt5dbus",
]
EXCLUDES = ["tkinter", "unittest", "pydoc", "PyQt5.QtNetwork", "PyQt5.QtQml", "PyQt5.QtQuick",
            "PyQt5.QtWebSockets", "PyQt5.QtSvg", "PyQt5.QtDBus", "PyQt5.QtPrintSupport"]

SPEC = r'''# generated by installer/build.py
DROP = %(drop)r

def keep(entry):
    name = entry[0].replace("\\", "/").lower()
    return not any(d in name for d in DROP)

a = Analysis([%(script)r], pathex=[%(root)r], datas=%(datas)r, excludes=%(excludes)r)
a.binaries = [b for b in a.binaries if keep(b)]
a.datas = [d for d in a.datas if keep(d)]
pyz = PYZ(a.pure)
'''

ONEDIR = r'''exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name=%(name)r, icon=%(icon)r,
          version=%(version)r, console=False, upx=False)
coll = COLLECT(exe, a.binaries, a.datas, name=%(name)r, upx=False)
'''

ONEFILE = r'''exe = EXE(pyz, a.scripts, a.binaries, a.datas, [], name=%(name)r, icon=%(icon)r,
          version=%(version)r, console=False, upx=False, runtime_tmpdir=None)
'''


def version():
    with open(os.path.join(ROOT, "enigma_timer", "__init__.py")) as f:
        return re.search(r'VERSION\s*=\s*"([^"]+)"', f.read()).group(1)


def version_file(ver):
    nums = [int(x) for x in re.findall(r"\d+", ver)][:4]
    nums += [0] * (4 - len(nums))
    dotted = ".".join(str(n) for n in nums)
    text = """VSVersionInfo(
  ffi=FixedFileInfo(filevers=%(t)s, prodvers=%(t)s, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
      StringStruct('CompanyName', 'Enigma Studio'),
      StringStruct('FileDescription', 'Enigma Cube'),
      StringStruct('FileVersion', '%(d)s'),
      StringStruct('ProductName', 'Enigma Cube'),
      StringStruct('ProductVersion', '%(d)s')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""" % {"t": repr(tuple(nums)), "d": dotted}
    path = os.path.join(BUILD, "version_info.txt")
    with open(path, "w") as f:
        f.write(text)
    return path


def build(name, script, datas, onefile, distpath, vfile):
    icon = os.path.join(ROOT, "assets", "app.ico")
    spec = SPEC % {"drop": DROP, "script": script, "root": ROOT, "datas": datas,
                   "excludes": EXCLUDES}
    spec += (ONEFILE if onefile else ONEDIR) % {"name": name, "icon": icon, "version": vfile}
    spec_path = os.path.join(BUILD, name + ".spec")
    with open(spec_path, "w") as f:
        f.write(spec)
    cmd = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean",
           "--workpath", os.path.join(BUILD, "work"), "--distpath", distpath, spec_path]
    print(">", " ".join(cmd), flush=True)
    subprocess.check_call(cmd, cwd=ROOT)


def folder_size(path):
    return sum(os.path.getsize(os.path.join(b, f)) for b, _d, fs in os.walk(path) for f in fs)


def main():
    ver = version()
    os.makedirs(BUILD, exist_ok=True)
    vfile = version_file(ver)
    assets = os.path.join(ROOT, "assets")

    print("\n[1/3] Enigma Cube %s" % ver, flush=True)
    dist = os.path.join(ROOT, "dist")
    build("EnigmaCube", os.path.join(ROOT, "main.py"), [(assets, "assets")], False, dist, vfile)
    app_dir = os.path.join(dist, "EnigmaCube")
    print("   app folder: %.1f MB" % (folder_size(app_dir) / 1048576.0))

    print("\n[2/3] Payload", flush=True)
    payload = os.path.join(BUILD, "payload.zip")
    with zipfile.ZipFile(payload, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for base, _dirs, files in os.walk(app_dir):
            for name in files:
                full = os.path.join(base, name)
                z.write(full, os.path.relpath(full, app_dir).replace(os.sep, "/"))
        z.writestr("payload.json", json.dumps({"version": ver}))
    print("   payload: %.1f MB" % (os.path.getsize(payload) / 1048576.0))

    print("\n[3/3] Setup", flush=True)
    out = os.path.join(ROOT, "Output")
    name = "EnigmaCube-Setup-%s" % ver
    datas = [(payload, "."), (os.path.join(assets, "icon.png"), ".")]
    build(name, os.path.join(INST, "setup_app.py"), datas, True, out, vfile)
    result = os.path.join(out, name + ".exe")
    print("\nDone: %s (%.1f MB)" % (result, os.path.getsize(result) / 1048576.0))


if __name__ == "__main__":
    main()
